name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build (github)
      run: npm run build:web

    - name: Build (github)
      run: npm run build:github

    - name: Build (webos)
      run: npm run build:webos

    - name: Build (tizen)
      run: npm run build:tizen

    - name: Build (plugins)
      run: npm run build:plugins

    - name: Build (doc)
      run: npm run build:doc

    - name: Run tests
      run: npm run test
